### ISSUE TITLE
Static linking in windows

### ISSUE THREAD

**Issue by sturner** [shadowmint/go-static-linking#1]
Any chance you could try this out on windows?  I'm having a fit right now trying to link a static library on windows.  Since the library is a "*.a' file, I'm assuming this was a standard linux static library.  If you get it to work on windows, do let me know.  I'm baffled at the moment.

Thanks!
Shane

**Comment by shadowmint** [comment]
Really? 

Hm. I'm pretty sure I had it working using gcc in mingw previously. I'll check later and see what's up if it's not working and update this ticket.

**Comment by shadowmint** [comment]
Added documentation on how to build on windows.
