### ISSUE TITLE
Unable to set a os env variable in #cgo directive

### ISSUE THREAD

**Issue by avikalar** [shadowmint/go-static-linking#2]
Hi, 

I have been trying to include an os env variable as part of the CGO build, but when I add path as 

```
// #cgo linux CFLAGS: -I $LIBHOME/include
// #cgo linux LDFLAGS: -L $LIBHOME/lib
```

go build . gives me header file not found, whereas when I try using 

```
// #cgo linux CFLAGS: -I ${LIBHOME}/include
// #cgo linux LDFLAGS: -L ${LIBHOME}/lib
```

the build returns a malformed cgo parameter error. In both cases I am unable to set the library path using an environment variable. Then, I bumped into your thread in stackoverflow(http://stackoverflow.com/questions/16747021/how-do-you-statically-link-a-c-library-in-go-using-cgo) and it seems to be working for you. Can you please help me out here ?

Thanks in advance,
Avinash K

**Comment by shadowmint** [comment]
@avikalar Have a look at how https://github.com/shadowmint/go-static-linking/blob/master/CMakeLists.txt#L44 works.

Notice that the #cgo directives are dynamically generated using absolute paths using the cmake templating system. I believe that this is currently the only way to make this work in a 'cross platform' manner.

I'm afraid I can't see what you're doing, so I can't really offer more help than that, but see that in https://github.com/shadowmint/go-static-linking/blob/master/demo/src/bridge/bridge.go.in the ${FOO} is replaced by cmake _only_ if a FOO is in scope when the configure_file() directive is invoked.

Obviously if you're doing the same thing, but you have a LIBHOME defined in your .in file and no LIBHOME variable, no replacement will happen.

&tldr: Use absolute paths in your cgo directives.
